#pragma once
#include "ext/imgui/imgui.h"
#include "ext/imgui/imgui_impl_win32.h"
#include "ext/minhook/minhook.h"
#include "ext/imgui/imgui_impl_dx11.h"
#include "ext/imgui/imgui_internal.h"
#include <Windows.h>
#include <dwmapi.h>
#include <d3d11.h>
#include <math.h>
#include <vector>
#include <iostream>
#include <d3d11.h>
#include <mutex>
#include <algorithm>
#include <cmath>
#include <DirectXMath.h>
#include <fstream>
#include <string>
#include "Misc.h"
#include "Offsets.h"